name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'
      - name: Run tests
        run: go test ./...